### ISSUE TITLE
Daemon Script nicht debian stretch kompatibel

### ISSUE THREAD

**Issue by gbrehmer** [mschlenstedt/LoxBerry-Plugin-WU4Lox#11]
Die Ausgabe von ifconfig hat sich geändert (kein addr: vor der IP):

jessie:
```
eth0      Link encap:Ethernet  HWaddr xxx
          inet addr:xxx  Bcast:xxx  Mask:xxx
          inet6 addr: xxx/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1823235745 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1824500714 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:175391034998 (163.3 GiB)  TX bytes:3687303492620 (3.3 TiB)
```

stretch:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet xxx  netmask xxx  broadcast xxx
        inet6 xxx  prefixlen 64  scopeid 0x20<link>
        ether xxx  txqueuelen 1000  (Ethernet)
        RX packets 331480  bytes 223251538 (212.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 153134  bytes 13626204 (12.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by gbrehmer** [comment]
Es gibt noch ein potentiell weiteres Problem: Das Skript startet nicht mehr beim Start des Rechners oder aber die Aktionen darin funktionieren nicht. Z.B. fehlt die RAM-Disk immer. Ich starte aktuell nach einem Restart das Skript noch zusätzlich per Hand. Habe noch nicht herausgefunden, ob es zwar ausgeführt wird, aber eventuell zu früh o.ä.

**Comment by mschlenstedt** [comment]
Bitte benutzt das Original-LoxBerry Image (Wheezy). Stretch wird aktuell nicht unterstützt. Ich werde das Plugin erst für die nächste LoxBerry-Version (0.4.0) anpassen. 0.4.0 wird dann auch offiziell auf Stretch basieren.

**Comment by gbrehmer** [comment]
Für meinen Fall sind diese Einschränkungen kein Problem, wollte sie nur mitteilen, damit man vor einem Update sich diese Themen schon einmal anschauen kann. Ich hab auch nie das Standard-Image eingesetzt, sondern bin nach der Anleitung zur Erstellung eines eigenen Images vorgegangen und hab mein vorhandenes Raspbian als Basis genommen.
