### ISSUE TITLE
Make DNSMasq optional

### ISSUE THREAD

**Issue by johny-mnemonic** [mschlenstedt/LoxBerry-Plugin-WU4Lox#12]
Would it be possible to make DNSMasq configuration optional?
I do not use Loxberry as my router, nor as my DNS server, so configuring DNSMasq in Loxberry is not of much use, as Miniserver is using main router for DNS. So I inserted that DNS redirect into main router.

Another thing is, that I am running docker with InfluxDB and Grafana on Loxberry as an alternative to stats plugin and enabling DNSMasq on Loxberry completely breaks communication between docker containers :-)

**Comment by mschlenstedt** [comment]
DNSMasq will be diabled in the next release if not in use by the plugin.

**Comment by johny-mnemonic** [comment]
The thing is, that it is used by the plugin and I don't see how this plugin can work without it by default, so I don't expect it to be removed completely.
That's why I asked if it can be made configurable for users, that do not want to have DNSMasq running and are willing to configure DNS manually.
