### ISSUE TITLE
WU4LOX 4 Beta auf LB1.0.1

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-WU4Lox#13]
Übergeben von https://github.com/mschlenstedt/Loxberry/issues/590, dort als User @Strike1988 erfasst (kein LoxBerry-Problem an sich) .

Könnte ein Problem mit dem wu4lox File in /opt/loxberry/system/apache2/sites-enabled sein.

Quote von Strike:

Raspi 3 / LAN
Folgendes wurde ausgegeben. 

/opt/loxberry/log/system_tmpfs/apache2/error.log :

[Thu Feb 15 20:06:43.530852 2018] [mpm_prefork:notice] [pid 608] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Thu Feb 15 20:06:43.531037 2018] [core:notice] [pid 608] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 15 20:06:51.324818 2018] [mpm_prefork:notice] [pid 608] AH00169: caught SIGTERM, shutting down
[Thu Feb 15 20:06:51.738438 2018] [mpm_prefork:notice] [pid 890] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Thu Feb 15 20:06:51.738579 2018] [core:notice] [pid 890] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 15 20:06:54.562178 2018] [mpm_prefork:emerg] [pid 904] (43)Identifier removed: AH00144: couldn't grab the accept mutex
[Thu Feb 15 20:06:54.571319 2018] [mpm_prefork:emerg] [pid 906] (43)Identifier removed: AH00144: couldn't grab the accept mutex
[Thu Feb 15 20:06:54.571287 2018] [mpm_prefork:emerg] [pid 905] (43)Identifier removed: AH00144: couldn't grab the accept mutex
[Thu Feb 15 20:06:54.746693 2018] [core:alert] [pid 890] AH00050: Child 904 returned a Fatal error... Apache is exiting!
[Thu Feb 15 20:06:54.746806 2018] [:emerg] [pid 890] AH02818: MPM run failed, exiting
[Thu Feb 15 20:06:54.748187 2018] [mpm_prefork:emerg] [pid 932] (22)Invalid argument: AH00144: couldn't grab the accept mutex
[Thu Feb 15 20:09:19.036955 2018] [core:warn] [pid 1064] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Feb 15 20:09:19.049414 2018] [mpm_prefork:notice] [pid 1064] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Thu Feb 15 20:09:19.049494 2018] [core:notice] [pid 1064] AH00094: Command line: '/usr/sbin/apache2'

**Comment by Strike1988** [comment]
@mschlenstedt Wäre das sehr viel Mühe und Aufwand den Cloud Emu auf die aktuelle Version anzupassen? Quasi die 4.0 Version fertig zu stellen. Dafür wäre ich dir sehr Dankbar. Aber da LoxBerry 1.X.X gerade viel arbeit macht, kann ich das auch verstehen.

**Comment by mschlenstedt** [comment]
Komtm mit der nächsten Version. Die Beta-4.0 läuft NICHT auf LB 1.0.
