### ISSUE TITLE
Vorschau

### ISSUE THREAD

**Issue by thmeger** [mschlenstedt/LoxBerry-Plugin-WU4Lox#14]
Software error:

Validation failed for type named Num declared in package Specio::Library::Builtins (/usr/share/perl5/Specio/Library/Builtins.pm) at line 135 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named Num declared in package Specio::Library::Builtins (/usr/share/perl5/Specio/Library/Builtins.pm) at line 135 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0xd4f7a0)', 'value', undef) called at (eval 193) line 84
DateTime::_check_from_epoch_params('epoch', undef, 'time_zone', 'local') called at /usr/lib/arm-linux-gnueabihf/perl5/5.24/DateTime.pm line 470
DateTime::from_epoch('DateTime', 'epoch', undef, 'time_zone', 'local') called at /opt/loxberry/webfrontend/htmlauth/plugins/wu4lox/show.cgi line 298

For help, please send mail to the webmaster ([no address given]), giving this error message and the time and date of the error.

**Comment by mschlenstedt** [comment]
Welche Plugin-Version?
Welche LoxBerry Version?
Welche Hardware-Architektur?

**Comment by thmeger** [comment]
Oh sorry. Die Infos sind untergegangen. 
Ist mein Problem :-)
Welche Plugin-Version? 4.0 Beta
Welche LoxBerry Version? 1.0.3.2
Welche Hardware-Architektur? pi 3

Deinstalliere mal 4.0 & versuche 3.6.1

**Comment by mschlenstedt** [comment]
Die Beta-4.0 läuft nicht auf LB1.0 - siehe hier: http://www.loxwiki.eu/display/LOXBERRY/Wunderground4Loxone
