### ISSUE TITLE
CloudEmulator

### ISSUE THREAD

**Issue by Strike1988** [mschlenstedt/LoxBerry-Plugin-WU4Lox#16]
Hinzufügen des CloudEmulators in die aktuelle Version.

**Comment by mschlenstedt** [comment]
Was bezweckst Du jetzt mit diesem Issue? Meist Du wenn Du mich unter Druck setzt geht es irgendwie schneller?

**Comment by Strike1988** [comment]
sorry, war nicht so gemeint. dachte als es mehr als to-do. ich weiss ja auch dass der loxberry an sich vorrang hat.
