### ISSUE TITLE
Cloud Weather Emulator funktioniert mit einem Raspberry 3 nicht richtig

### ISSUE THREAD

**Issue by leschNUX** [mschlenstedt/LoxBerry-Plugin-WU4Lox#29]
Hi,

wenn man das wu4lox auf einem Raspberry 3 betreibt und diesen per lan angeschlossen hat, statt wlan. Dann findet das Skript den falschen Adapter und trägt die lokale IP nicht in die /etc/dnsmasq.d/wu4lox.conf.

Es wird eingetragen:
address=/weather.loxone.com/

es muss aber dahinter noch die IP eintragen werden, sonst funktioniert kein dnsmasq
address=/weather.loxone.com/IP

Mit dieser Zeile findet er die richtige IP Adresse und trägt diese richtig ein.

ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1

Das ganze in der Datei /opt/loxberry/system/daemons/plugins/wu4lox in Zeile 102 und 105 austauschen:
OWNIP=`ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1`

Gruss

**Comment by mschlenstedt** [comment]
Danke. Ich schreibe die Routine gerade neu. Da werde ich das mit testen.

**Comment by mschlenstedt** [comment]
Hi,

kannst Du Dich bitte mal per Putty auf die Konsole einloggen und dann folgenden Befehl ausführen:

```ifconfig```

Das Ergebnis bitte mal schicken.

**Comment by mschlenstedt** [comment]
Ah, hat sich erledigt. Danke.

**Comment by mschlenstedt** [comment]
Sollte mit dem nächsten Update behoben sein.
