### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by defcore** [mschlenstedt/LoxBerry-Plugin-WU4Lox#31]
Es wird folgenden Fehlermeldung in der Pluginseite angezeigt:

HTML::Template::param() : attempt to set parameter 'server.stationid' with an array ref - parameter is not a TMPL_LOOP! at /opt/loxberry/webfrontend/htmlauth/plugins/wu4lox/index.cgi line 552.

Version: Wunderground4Loxone V4.1.0

**Comment by Strike1988** [comment]
Workarround: 
1. Plugin deinstallieren
2. Plugin erneut installieren
3. Bei Einrichtung des Plugins: Wetterstation durch **IP-Adresse** beziehen, also keine koordinaten eingeben

**Comment by defcore** [comment]
Danke!

**Comment by mschlenstedt** [comment]
Liegt an den Kommata und einem fehlerhaften Perlmodul. Fixe ich in der nächsten Version.
