### ISSUE TITLE
Kommas statt Punkte in Koordinaten

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-WU4Lox#32]
Kommas statt Punkt in den Koordinaten führt zu

![image](https://user-images.githubusercontent.com/14220265/39116231-2fc51766-46e4-11e8-9c24-1ce5f44be35a.png)

Fehler "Could not find weather station with this id"

![image](https://user-images.githubusercontent.com/14220265/39116284-5997adce-46e4-11e8-96df-45930dd1ab99.png)

**Comment by mschlenstedt** [comment]
Danke, werde die Kommata ersetzen.
