### ISSUE TITLE
Koordinaten werden auch in die Station-ID übernommen

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-WU4Lox#33]
Fehler bei der Übernahme aus Google Maps:

1. Adresssuche via Maps-Button durchführen und "Apply"

![image](https://user-images.githubusercontent.com/14220265/39116465-d25d9ade-46e4-11e8-9447-f5af6a1b2965.png)

2. Speichern 

![image](https://user-images.githubusercontent.com/14220265/39116483-db0120de-46e4-11e8-8835-0d161c084e5a.png)

3. Nun wurden die Koordinaten fälschlicherweise(?) auch in die Station ID übernommen

![image](https://user-images.githubusercontent.com/14220265/39116580-1cd1ae98-46e5-11e8-9dc5-06bf413ef928.png)

Ich weiß nicht, ob das passt?

**Comment by christianTF** [comment]
PS: Es scheint so, dass beim Wechsel von "Station-ID" auf "Coordinates" die STATIONID im Configfile auch mit den Koordinaten (samt) Komma überschrieben wird, und dann kommen die Config::Simple Array-Probleme bei HTML::Template.

![image](https://user-images.githubusercontent.com/14220265/39117603-a7837e70-46e7-11e8-8807-da922e851c08.png)

**Comment by mschlenstedt** [comment]
Ja, aktuell ist das so. Ist unschön, muss ich dann aber erst neu schreiben. 

Der Fehler kommt, weil das blöde SimpleConfig Modul die Anführungszeichenzeichen beim zurückspeichern nicht wieder setzt. So ein Müll.
