### ISSUE TITLE
Komma in Station ID

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-WU4Lox#34]
Wenn ich es irgendwie schaffe, dass ich ein Komma in die Station-ID bekomme (z.B. durch die Übernahme aus Maps), tritt das Config::Simple Array-Problem auf (String wird als Array gelesen).

![image](https://user-images.githubusercontent.com/14220265/39116776-8ff8a9d0-46e5-11e8-97ad-ffa78df81cc0.png)

![image](https://user-images.githubusercontent.com/14220265/39116850-bcb39e30-46e5-11e8-97ab-d2b7d088d97d.png)

Da kommt man auch nicht mehr raus, außer wenn man das Config-File manuell bearbeitet und das Komma entfernt.

**Comment by mschlenstedt** [comment]
Danke, hab den Fehler schon gefunden.
