### ISSUE TITLE
Theme Preview: Validation failed for type named Num declared in package Specio::Library::Builtins

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-WU4Lox#35]
![image](https://user-images.githubusercontent.com/14220265/39117191-b4c84936-46e6-11e8-970e-627df464d27f.png)

Config File (API-Key entfernt):

```
; Config::Simple 4.59
; Mon Apr 23 11:07:39 2018

[PLUGIN]
SCRIPTNAME=wu4lox

[WEB]
ICONSET=silver
THEME=dark

[SERVER]
SENDHFC=
METRIC=1
STATIONID=pws:IOBERSTE149
EMU=0
WUAPIKEY=<geheim>
COORDLAT=48.3150461
CRON=3
SENDUDP=0
GETWUDATA=0
STATIONTYP=statid
UDPPORT=7000
WULANG=DL
COORDLONG=14.2307916
SENDDFC=
WUURL=http://api.wunderground.com/api
```

**Comment by mschlenstedt** [comment]
Hast du schon mal Wetterdaten abgeholt bevor du auf Preview geklickt hast?

**Comment by christianTF** [comment]
Aha, so geht das!

**Comment by mschlenstedt** [comment]
Naja, er sollte dir auch ohne erste Abholung etwas anzeigen. Deswegen liefere ich DummyDaten mit.

**Comment by mschlenstedt** [comment]
Ich kann das nicht reproduzieren. Wie hast Du das genau angestellt?

**Comment by christianTF** [comment]
Ich weiß es nicht - ich hab nach der Installation den API-Key und die PWS angegeben, aber Fetch habe ich abgeschaltet gelassen.
Da kam dann dieser Fehler. Jetzt bring ich es (trotz fetch aus und löschen der data/ Dateien) auch nicht mehr hin. 

Allerdings weiß ich auch nicht, wo du die Daten genau herholst, weil egal was ich lösche, steht da jetzt immer noch "Puchenau" und die Werte von 7:00 Uhr.

Egal, vielleicht ist es auch implizit mit deinen Fixes schon mitgefixt.
Wenn ich's wieder schaffe, meld ich mich :-)
