### ISSUE TITLE
Software error

### ISSUE THREAD

**Issue by heinzdeg** [mschlenstedt/LoxBerry-Plugin-WU4Lox#40]
LoxBerry V1.2.1 - Wunderground4Loxone V4.1.0

Software error:

HTML::Template::param() : attempt to set parameter 'server.stationid' with an array ref - parameter is not a TMPL_LOOP! at /opt/loxberry/webfrontend/htmlauth/plugins/wu4lox/index.cgi line 552.
Depending of what you have done, report this error to the plugin developer or the LoxBerry-Core team.
Further information you may find in the error logs.

![bildschirmfoto 2018-04-25 um 21 15 44](https://user-images.githubusercontent.com/38735521/39267688-d96ff34a-48cd-11e8-8e03-ac7dab364207.png)

**Comment by mschlenstedt** [comment]
Danke, ist bereits gefixt.

**Comment by heinzdeg** [comment]
Hallo,

vielen Dank für die Info.
Kann ich die gefixte Version schon irgendwo downloaden und testen?

VG
Heinz
