### ISSUE TITLE
Enhancement: Eigenen vhost auf einstellbarer Adresse / Port für die Wettervorhersage

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/LoxBerry-Plugin-WU4Lox#5]
Siehe   https://github.com/mschlenstedt/LoxBerry-Plugin-WU4Lox/pull/4

**Comment by mschlenstedt** [comment]
Werde ich nicht implementieren. "Spezial"-Anwendung von Dir, um die Du dich selbst kümmern musst :-)
